import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router'
import { fetchEntry } from '../../utils/fetchEntry';
import { BLOCKS } from '@contentful/rich-text-types';
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';



export async function getServerSideProps(context) {
  return {
    props: {},
  };
}

export default function Slug(props) {

  const router = useRouter();


  const [blogPost, setBlogPost] = useState(null);

  function fetchPost(post) {
    const data = fetchEntry(post).then((entry) => {
      const rawRichTextField = entry.fields.body;
      return rawRichTextField;
    })
      .then((renderedHtml) => {
        setBlogPost(renderedHtml)
      })
  }


  useEffect(() => {
    if (!blogPost) fetchPost(router?.query?.postId)
  }, [blogPost, router?.query?.postId])

  const options = {
    renderNode: {
      [BLOCKS.PARAGRAPH]: (node, children) => (
        <p>{children}</p>
      ),

      [BLOCKS.EMBEDDED_ASSET]: (node, children) => {
        // render the EMBEDDED_ASSET as you need
        return (
          <img
            src={`https://${node?.data?.target?.fields?.file?.url}` ?? `https://${blogPost?.blogImage?.fields?.file?.url}`}
            height={node?.data?.target?.fields?.file?.details?.image?.height}
            width={node?.data?.target?.fields?.file?.details?.image?.width}
            alt={node?.data?.target?.fields?.description}
          />
        );
      },
    },
  };


  return (

    <>
      {/* <Header /> */}
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <p>{blogPost?.fields?.date}</p>
          <p>{blogPost?.fields?.author}</p>
          <p>{blogPost?.fields?.title}</p>
          <article>
            {/* {blogPost?.blogImage?.fields?.file?.url ? <div style={{ width: '25%', float: 'left', paddingRight: '20px' }}><img src={blogPost?.blogImage?.fields?.file?.url} style={{ maxWidth: '100%' }} /></div> : null} */}
            {documentToReactComponents(blogPost, options)}
            {/* <div dangerouslySetInnerHTML={{ __html: blogPost }} /> */}
          </article>
        </main>

      </div>
    </>
  )
}
